
import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Globe, Building, ArrowRight } from 'lucide-react';
import { initScrollAnimations } from '../utils/scrollAnimations';

const Clients = () => {
  useEffect(() => {
    // Initialize scroll animations
    initScrollAnimations();
    // Scroll to top when component mounts
    window.scrollTo(0, 0);
  }, []);

  // Dummy client data
  const clients = [
    { name: "TechCorp Global", industry: "Technology", logo: "TC" },
    { name: "FinanceWise Inc.", industry: "Finance", logo: "FW" },
    { name: "HealthPlus Systems", industry: "Healthcare", logo: "HP" },
    { name: "Retail Innovations", industry: "Retail", logo: "RI" },
    { name: "EnergyNow Corp", industry: "Energy", logo: "EN" },
    { name: "Logistics Pro", industry: "Logistics", logo: "LP" },
    { name: "Media Dynamics", industry: "Media", logo: "MD" },
    { name: "Manufacturing Excellence", industry: "Manufacturing", logo: "ME" }
  ];

  // Dummy partner data
  const partners = [
    { name: "Cloud Solutions Inc.", type: "Technology Partner", logo: "CS" },
    { name: "DataFlow Systems", type: "Integration Partner", logo: "DF" },
    { name: "Global Consulting Group", type: "Consulting Partner", logo: "GC" },
    { name: "Secure Networks Ltd", type: "Infrastructure Partner", logo: "SN" }
  ];

  // Dummy distributor data
  const distributors = [
    { name: "NorthAm Solutions", region: "North America", logo: "NA" },
    { name: "EuroTech Distributors", region: "Europe", logo: "ET" },
    { name: "Asia Pacific Systems", region: "Asia Pacific", logo: "AP" },
    { name: "MENA Technology Group", region: "Middle East & Africa", logo: "MT" }
  ];

  // Dummy testimonials
  const testimonials = [
    {
      quote: "Implementing Ubertrix's AI solutions has transformed our data analysis capabilities and improved decision-making across the organization.",
      author: "Sarah Johnson",
      title: "CTO, TechCorp Global",
      logo: "TC"
    },
    {
      quote: "The insights generated by Ubertrix's platform have helped us identify new market opportunities and increase revenue by 35% in just six months.",
      author: "Michael Chen",
      title: "Data Science Director, FinanceWise Inc.",
      logo: "FW"
    },
    {
      quote: "Ubertrix's customer support is exceptional. They worked closely with our team to customize their solutions to our specific healthcare compliance requirements.",
      author: "Dr. Emily Rodriguez",
      title: "Innovation Officer, HealthPlus Systems",
      logo: "HP"
    }
  ];

  return (
    <>
      {/* Header Section */}
      <section className="pt-32 pb-20 bg-gradient-to-b from-black to-ubertrix-background">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-6 animate-on-scroll">
            Our <span className="text-ubertrix-primary">Clients & Partners</span>
          </h1>
          <p className="text-gray-300 text-lg max-w-2xl mx-auto animate-on-scroll delay-100">
            Discover the organizations that trust Ubertrix to deliver cutting-edge AI solutions across various industries.
          </p>
        </div>
      </section>

      {/* Clients Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-4 animate-on-scroll">Featured Clients</h2>
          <p className="text-gray-300 text-center mb-12 max-w-xl mx-auto animate-on-scroll delay-100">
            Industry leaders who have transformed their operations with our AI solutions.
          </p>
          
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mb-12">
            {clients.map((client, index) => (
              <div 
                key={index} 
                className="bg-ubertrix-muted bg-opacity-20 p-6 rounded-lg text-center card-hover animate-on-scroll"
                style={{ animationDelay: `${index * 0.1}s` }}
              >
                <div className="bg-gradient-to-br from-ubertrix-primary to-ubertrix-secondary w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-black font-bold text-xl">{client.logo}</span>
                </div>
                <h3 className="font-semibold mb-1">{client.name}</h3>
                <p className="text-gray-400 text-sm">{client.industry}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-black">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-4 animate-on-scroll">Client Testimonials</h2>
          <p className="text-gray-300 text-center mb-12 max-w-xl mx-auto animate-on-scroll delay-100">
            Hear what our clients have to say about their experience with Ubertrix.
          </p>
          
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div 
                key={index}
                className="bg-ubertrix-muted bg-opacity-20 p-8 rounded-lg relative animate-on-scroll"
                style={{ animationDelay: `${index * 0.2}s` }}
              >
                <div className="absolute -top-5 -left-5 text-6xl text-ubertrix-primary opacity-50">"</div>
                <p className="text-gray-300 mb-6 relative z-10">
                  {testimonial.quote}
                </p>
                <div className="flex items-center">
                  <div className="bg-gradient-to-br from-ubertrix-primary to-ubertrix-secondary w-12 h-12 rounded-full flex items-center justify-center mr-4">
                    <span className="text-black font-bold text-sm">{testimonial.logo}</span>
                  </div>
                  <div>
                    <h4 className="font-semibold">{testimonial.author}</h4>
                    <p className="text-gray-400 text-sm">{testimonial.title}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Partners and Distributors Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
            {/* Partners */}
            <div>
              <div className="flex items-center mb-8 animate-on-scroll">
                <div className="bg-ubertrix-primary bg-opacity-20 w-12 h-12 rounded-full flex items-center justify-center mr-4">
                  <Building className="text-ubertrix-primary" size={24} />
                </div>
                <div>
                  <h2 className="text-3xl font-bold">Our Partners</h2>
                  <p className="text-gray-400">Strategic alliances that enhance our AI ecosystem</p>
                </div>
              </div>
              
              <div className="space-y-4">
                {partners.map((partner, index) => (
                  <div 
                    key={index}
                    className="bg-ubertrix-muted bg-opacity-20 p-5 rounded-lg flex items-center animate-on-scroll"
                    style={{ animationDelay: `${index * 0.15}s` }}
                  >
                    <div className="bg-gradient-to-br from-ubertrix-primary to-ubertrix-secondary w-14 h-14 rounded-full flex items-center justify-center mr-4 flex-shrink-0">
                      <span className="text-black font-bold">{partner.logo}</span>
                    </div>
                    <div>
                      <h3 className="font-semibold">{partner.name}</h3>
                      <p className="text-gray-400 text-sm">{partner.type}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
            {/* Distributors */}
            <div>
              <div className="flex items-center mb-8 animate-on-scroll">
                <div className="bg-ubertrix-primary bg-opacity-20 w-12 h-12 rounded-full flex items-center justify-center mr-4">
                  <Globe className="text-ubertrix-primary" size={24} />
                </div>
                <div>
                  <h2 className="text-3xl font-bold">Global Distributors</h2>
                  <p className="text-gray-400">Bringing Ubertrix solutions to markets worldwide</p>
                </div>
              </div>
              
              <div className="space-y-4">
                {distributors.map((distributor, index) => (
                  <div 
                    key={index}
                    className="bg-ubertrix-muted bg-opacity-20 p-5 rounded-lg flex items-center animate-on-scroll"
                    style={{ animationDelay: `${index * 0.15}s` }}
                  >
                    <div className="bg-gradient-to-br from-ubertrix-primary to-ubertrix-secondary w-14 h-14 rounded-full flex items-center justify-center mr-4 flex-shrink-0">
                      <span className="text-black font-bold">{distributor.logo}</span>
                    </div>
                    <div>
                      <h3 className="font-semibold">{distributor.name}</h3>
                      <p className="text-gray-400 text-sm">{distributor.region}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Industries Section */}
      <section className="py-20 bg-black">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-4 animate-on-scroll">Industries We Serve</h2>
          <p className="text-gray-300 text-center mb-12 max-w-xl mx-auto animate-on-scroll delay-100">
            Our AI solutions empower organizations across diverse industries.
          </p>
          
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {['Healthcare', 'Finance', 'Retail', 'Manufacturing', 'Energy', 'Logistics', 'Media', 'Technology'].map((industry, index) => (
              <div 
                key={index}
                className="bg-ubertrix-muted bg-opacity-20 p-6 rounded-lg text-center card-hover animate-on-scroll"
                style={{ animationDelay: `${index * 0.1}s` }}
              >
                <h3 className="font-semibold text-lg mb-2 text-ubertrix-primary">{industry}</h3>
                <div className="bg-gray-700 h-1 w-12 mx-auto rounded-full mb-3"></div>
                <p className="text-gray-400 text-sm">Customized AI solutions for the {industry.toLowerCase()} sector</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-ubertrix-muted to-black">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6 animate-on-scroll">
            Join Our Growing Network of <span className="text-ubertrix-primary">Success Stories</span>
          </h2>
          <p className="text-gray-300 mb-8 max-w-xl mx-auto animate-on-scroll delay-100">
            Ready to transform your business with cutting-edge AI solutions?
          </p>
          <div className="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-4 animate-on-scroll delay-200">
            <Link to="/contact" className="btn-primary flex items-center justify-center">
              Become a Client <ArrowRight className="ml-2" size={18} />
            </Link>
            <Link to="/contact" className="btn-outline flex items-center justify-center">
              Partner With Us
            </Link>
          </div>
        </div>
      </section>
    </>
  );
};

export default Clients;
